apiVersion: v1
kind: Service
metadata:
  name: nodejs-loadbalancer
  labels:
      io.kompose.service: nodejs
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7080
  selector:
    io.kompose.service: nodejs
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost